"""Parche para cuaderno 01: mejoras robustez scraping YouTube con yt-dlp."""
import json
from pathlib import Path

NB_PATH = Path(r'c:\usr\ths_mia_fiis\pln\trabajo\Cuadernos\01_scraping_youtube_politica_farandula.ipynb')

with open(NB_PATH, encoding='utf-8') as f:
    nb = json.load(f)

def src(lines):
    """Convierte lista de líneas de celda a texto para comparación."""
    return ''.join(lines)

# ──────────────────────────────────────────────────────────────────────────────
# CELDA 2: Instalación — agregar youtube-transcript-api como fallback
# ──────────────────────────────────────────────────────────────────────────────
CELL_INSTALL = [
    "# Instalación de librerías del proyecto\n",
    "# youtube-transcript-api es un scraper sin API key (fallback para transcripciones)\n",
    "!pip install -q pandas selenium beautifulsoup4 webdriver-manager yt-dlp tqdm youtube-transcript-api\n",
]

# ──────────────────────────────────────────────────────────────────────────────
# CELDA 7: Selenium — anti-bot mejorado + WebDriverWait
# ──────────────────────────────────────────────────────────────────────────────
CELL_SELENIUM = [
    "UA = (\n",
    "    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '\n",
    "    'AppleWebKit/537.36 (KHTML, like Gecko) '\n",
    "    'Chrome/124.0.0.0 Safari/537.36'\n",
    ")\n",
    "\n",
    "\n",
    "def iniciar_driver(headless=True):\n",
    "    from selenium import webdriver\n",
    "    from selenium.webdriver.chrome.service import Service\n",
    "    from webdriver_manager.chrome import ChromeDriverManager\n",
    "\n",
    "    options = webdriver.ChromeOptions()\n",
    "    if headless:\n",
    "        options.add_argument('--headless=new')\n",
    "    options.add_argument('--disable-gpu')\n",
    "    options.add_argument('--no-sandbox')\n",
    "    options.add_argument('--disable-dev-shm-usage')\n",
    "    options.add_argument('--window-size=1400,1000')\n",
    "    options.add_argument('--lang=es-PE')\n",
    "    options.add_argument(f'--user-agent={UA}')\n",
    "    # Ocultar señales de automatización\n",
    "    options.add_experimental_option('excludeSwitches', ['enable-automation'])\n",
    "    options.add_experimental_option('useAutomationExtension', False)\n",
    "    service = Service(ChromeDriverManager().install())\n",
    "    driver = webdriver.Chrome(service=service, options=options)\n",
    "    # Eliminar propiedad webdriver del navegador\n",
    "    driver.execute_cdp_cmd(\n",
    "        'Page.addScriptToEvaluateOnNewDocument',\n",
    "        {'source': 'Object.defineProperty(navigator, \"webdriver\", {get: () => undefined})'}\n",
    "    )\n",
    "    return driver\n",
    "\n",
    "\n",
    "def buscar_canales_youtube(consulta, n_scrolls=2, headless=True):\n",
    "    from selenium.webdriver.common.by import By\n",
    "    from selenium.webdriver.support.ui import WebDriverWait\n",
    "    from selenium.webdriver.support import expected_conditions as EC\n",
    "\n",
    "    driver = iniciar_driver(headless=headless)\n",
    "    try:\n",
    "        # &sp=EgIQAg%3D%3D filtra resultados por tipo 'Canal'\n",
    "        url = ('https://www.youtube.com/results?search_query='\n",
    "               + quote_plus(consulta) + '&sp=EgIQAg%3D%3D')\n",
    "        driver.get(url)\n",
    "        try:\n",
    "            WebDriverWait(driver, 10).until(\n",
    "                EC.presence_of_element_located((By.TAG_NAME, 'ytd-channel-renderer'))\n",
    "            )\n",
    "        except Exception:\n",
    "            time.sleep(4)  # fallback si ytd-channel-renderer no aparece\n",
    "        for _ in range(n_scrolls):\n",
    "            driver.execute_script('window.scrollTo(0, document.documentElement.scrollHeight);')\n",
    "            time.sleep(2)\n",
    "        html = driver.page_source\n",
    "    finally:\n",
    "        driver.quit()\n",
    "\n",
    "    soup = BeautifulSoup(html, 'html.parser')\n",
    "    filas = []\n",
    "    for a in soup.find_all('a', href=True):\n",
    "        href = a['href']\n",
    "        texto = a.get_text(' ', strip=True)\n",
    "        if ('/@' in href or '/channel/' in href or '/c/' in href) and texto:\n",
    "            if href.startswith('/'):\n",
    "                href = 'https://www.youtube.com' + href\n",
    "            filas.append({'consulta': consulta, 'nombre': texto, 'url': href.split('?')[0]})\n",
    "    return pd.DataFrame(filas).drop_duplicates('url')\n",
    "\n",
    "\n",
    "consultas = [\n",
    "    'politica peru analisis canal youtube',\n",
    "    'noticias politica peru youtube',\n",
    "    'Marco Sifuentes Ocram YouTube Peru',\n",
    "    'Curwen YouTube Peru canal oficial',\n",
    "    'Rosa Maria Palacios Sin Guion YouTube Peru',\n",
    "    'Hablando Huevadas YouTube Peru canal oficial',\n",
    "    'Cacas youtuber peruano canal oficial YouTube',\n",
    "    'farandula peru programa youtube',\n",
    "    'Magaly Amor y Fuego America Hoy YouTube Peru',\n",
    "    'youtubers peruanos viajes Misias Buen Viaje Viaja y Prueba',\n",
    "]\n",
]

# ──────────────────────────────────────────────────────────────────────────────
# CELDA 10: listar_videos_canal — yt-dlp robusto
# ──────────────────────────────────────────────────────────────────────────────
CELL_LISTAR = [
    "import yt_dlp\n",
    "\n",
    "# User-Agent compartido con Selenium para consistencia\n",
    "YT_HEADERS = {\n",
    "    'User-Agent': (\n",
    "        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '\n",
    "        'AppleWebKit/537.36 (KHTML, like Gecko) '\n",
    "        'Chrome/124.0.0.0 Safari/537.36'\n",
    "    )\n",
    "}\n",
    "\n",
    "\n",
    "def _normalizar_url_canal(channel_url):\n",
    "    \"\"\"Garantiza que la URL apunte a la pestaña /videos del canal.\"\"\"\n",
    "    base = channel_url.rstrip('/')\n",
    "    # Eliminar pestañas ya presentes para evitar duplicar\n",
    "    for sufijo in ('/videos', '/streams', '/shorts', '/playlists'):\n",
    "        if base.endswith(sufijo):\n",
    "            base = base[: -len(sufijo)]\n",
    "    return base + '/videos'\n",
    "\n",
    "\n",
    "def listar_videos_canal(channel_url, max_videos=15):\n",
    "    url_videos = _normalizar_url_canal(channel_url)\n",
    "    opciones = {\n",
    "        'quiet': True,\n",
    "        'no_warnings': True,\n",
    "        # 'in_playlist' es la forma correcta en yt-dlp >= 2023\n",
    "        'extract_flat': 'in_playlist',\n",
    "        'playlist_items': f'1:{max_videos}',\n",
    "        'skip_download': True,\n",
    "        'ignoreerrors': True,\n",
    "        'extractor_retries': 3,\n",
    "        'http_headers': YT_HEADERS,\n",
    "        'sleep_interval': 1,\n",
    "        'max_sleep_interval': 3,\n",
    "    }\n",
    "    try:\n",
    "        with yt_dlp.YoutubeDL(opciones) as ydl:\n",
    "            info = ydl.extract_info(url_videos, download=False)\n",
    "    except Exception as exc:\n",
    "        print(f'  ✗ Error extrayendo canal {channel_url}: {exc}')\n",
    "        return []\n",
    "\n",
    "    if not info:\n",
    "        return []\n",
    "\n",
    "    filas = []\n",
    "    for item in info.get('entries', []) or []:\n",
    "        if not item:\n",
    "            continue\n",
    "        video_id = item.get('id')\n",
    "        if not video_id:\n",
    "            continue\n",
    "        filas.append({\n",
    "            'video_id': video_id,\n",
    "            'url': f'https://www.youtube.com/watch?v={video_id}',\n",
    "            'title': item.get('title'),\n",
    "            'upload_date': item.get('upload_date'),\n",
    "            'duration': item.get('duration'),\n",
    "            'view_count': item.get('view_count'),\n",
    "            'channel_url': channel_url,\n",
    "        })\n",
    "    return filas\n",
]

# ──────────────────────────────────────────────────────────────────────────────
# CELDA 13: descargar_subtitulos + parseo VTT
# ──────────────────────────────────────────────────────────────────────────────
CELL_SUBS = [
    "SUBS_DIR = RAW_DIR / 'subtitulos'\n",
    "SUBS_DIR.mkdir(parents=True, exist_ok=True)\n",
    "\n",
    "\n",
    "def descargar_subtitulos(video_url, video_id):\n",
    "    \"\"\"Descarga subtítulos en español. Intenta manuales primero, luego auto.\n",
    "    Devuelve el Path al .vtt o None si no hay subtítulos disponibles.\n",
    "    \"\"\"\n",
    "    outtmpl = str(SUBS_DIR / f'{video_id}.%(ext)s')\n",
    "    opciones = {\n",
    "        'quiet': True,\n",
    "        'no_warnings': True,\n",
    "        'skip_download': True,\n",
    "        'writesubtitles': True,\n",
    "        'writeautomaticsub': True,\n",
    "        # es-419 = español latinoamericano (incluye Perú)\n",
    "        'subtitleslangs': ['es', 'es-419', 'es-PE'],\n",
    "        'subtitlesformat': 'vtt',\n",
    "        'outtmpl': outtmpl,\n",
    "        'ignoreerrors': True,\n",
    "        'extractor_retries': 3,\n",
    "        'http_headers': YT_HEADERS,\n",
    "        'sleep_interval': 1,\n",
    "        'max_sleep_interval': 3,\n",
    "    }\n",
    "    try:\n",
    "        with yt_dlp.YoutubeDL(opciones) as ydl:\n",
    "            ydl.download([video_url])\n",
    "    except Exception:\n",
    "        pass  # ignoreerrors ya captura la mayoría; este bloque es doble seguro\n",
    "    archivos = sorted(SUBS_DIR.glob(f'{video_id}*.vtt'))\n",
    "    return archivos[0] if archivos else None\n",
    "\n",
    "\n",
    "def descargar_subtitulos_transcript_api(video_id):\n",
    "    \"\"\"Fallback: obtiene transcripción vía youtube-transcript-api.\n",
    "    Devuelve lista de segmentos o [] si no está disponible.\n",
    "    \"\"\"\n",
    "    try:\n",
    "        from youtube_transcript_api import YouTubeTranscriptApi, NoTranscriptFound\n",
    "        transcript_list = YouTubeTranscriptApi.list_transcripts(video_id)\n",
    "        # Prioridad: manual es > generado es\n",
    "        try:\n",
    "            t = transcript_list.find_manually_created_transcript(['es', 'es-419', 'es-PE'])\n",
    "        except NoTranscriptFound:\n",
    "            t = transcript_list.find_generated_transcript(['es', 'es-419', 'es-PE'])\n",
    "        return [{'start': s['start'], 'duration': s['duration'], 'text': s['text']}\n",
    "                for s in t.fetch()]\n",
    "    except Exception:\n",
    "        return []\n",
    "\n",
    "\n",
    "def tiempo_a_segundos(valor):\n",
    "    partes = valor.replace(',', '.').split(':')\n",
    "    partes = [float(p) for p in partes]\n",
    "    if len(partes) == 3:\n",
    "        h, m, s = partes\n",
    "    else:\n",
    "        h, m, s = 0, partes[0], partes[1]\n",
    "    return h * 3600 + m * 60 + s\n",
    "\n",
    "\n",
    "def limpiar_linea_vtt(linea):\n",
    "    linea = re.sub(r'<[^>]+>', '', linea)        # tags HTML/VTT como <c>, <b>\n",
    "    linea = re.sub(r'&amp;', '&', linea)\n",
    "    linea = re.sub(r'&nbsp;', ' ', linea)\n",
    "    linea = re.sub(r'\\s+', ' ', linea).strip()\n",
    "    return linea\n",
    "\n",
    "\n",
    "def leer_vtt(path):\n",
    "    texto = path.read_text(encoding='utf-8', errors='ignore')\n",
    "    bloques = re.split(r'\\n\\s*\\n', texto)\n",
    "    segmentos = []\n",
    "    vistos = set()\n",
    "    patron_tiempo = re.compile(\n",
    "        r'(\\d{2}:\\d{2}:\\d{2}\\.\\d{3}|\\d{2}:\\d{2}\\.\\d{3})'\n",
    "        r'\\s+-->\\s+'\n",
    "        r'(\\d{2}:\\d{2}:\\d{2}\\.\\d{3}|\\d{2}:\\d{2}\\.\\d{3})'\n",
    "    )\n",
    "    for bloque in bloques:\n",
    "        lineas = [ln.strip() for ln in bloque.splitlines() if ln.strip()]\n",
    "        if not lineas:\n",
    "            continue\n",
    "        match = None\n",
    "        idx = 0\n",
    "        for i, linea in enumerate(lineas):\n",
    "            match = patron_tiempo.search(linea)\n",
    "            if match:\n",
    "                idx = i\n",
    "                break\n",
    "        if not match:\n",
    "            continue\n",
    "        start = tiempo_a_segundos(match.group(1))\n",
    "        end = tiempo_a_segundos(match.group(2))\n",
    "        frase = ' '.join(limpiar_linea_vtt(ln) for ln in lineas[idx + 1:])\n",
    "        frase = re.sub(r'\\s+', ' ', frase).strip()\n",
    "        # Deduplicar por (tiempo_redondeado, texto_normalizado)\n",
    "        clave = (round(start, 1), frase.lower())\n",
    "        if frase and clave not in vistos:\n",
    "            vistos.add(clave)\n",
    "            segmentos.append({'start': start, 'duration': max(end - start, 0.1), 'text': frase})\n",
    "    return segmentos\n",
]

# ──────────────────────────────────────────────────────────────────────────────
# CELDA 14: loop de transcripciones — con fallback a youtube-transcript-api
# ──────────────────────────────────────────────────────────────────────────────
CELL_LOOP = [
    "def hash_texto(texto):\n",
    "    return hashlib.md5(texto.encode('utf-8')).hexdigest()\n",
    "\n",
    "\n",
    "transcripciones = []\n",
    "sin_subs = []\n",
    "\n",
    "for _, video in tqdm(videos_df.iterrows(), total=len(videos_df)):\n",
    "    vid = video['video_id']\n",
    "    segmentos = []\n",
    "    fuente_subs = None\n",
    "\n",
    "    # --- Intento 1: yt-dlp (subtítulos del archivo .vtt) ---\n",
    "    try:\n",
    "        vtt_path = descargar_subtitulos(video['url'], vid)\n",
    "        if vtt_path:\n",
    "            segmentos = leer_vtt(vtt_path)\n",
    "            fuente_subs = 'yt-dlp-vtt'\n",
    "    except Exception as exc:\n",
    "        print(f'  yt-dlp falló en {vid}: {exc}')\n",
    "\n",
    "    # --- Intento 2: youtube-transcript-api como fallback ---\n",
    "    if not segmentos:\n",
    "        segmentos = descargar_subtitulos_transcript_api(vid)\n",
    "        if segmentos:\n",
    "            fuente_subs = 'transcript-api'\n",
    "\n",
    "    texto = ' '.join(seg['text'] for seg in segmentos)\n",
    "    if len(texto) < 200:\n",
    "        sin_subs.append(vid)\n",
    "        continue\n",
    "\n",
    "    transcripciones.append({\n",
    "        'video_id': vid,\n",
    "        'url': video['url'],\n",
    "        'title': video.get('title'),\n",
    "        'channel_title': video.get('channel_title'),\n",
    "        'categoria_fuente': video.get('categoria_fuente'),\n",
    "        'fuente_subs': fuente_subs,\n",
    "        'text_hash': hash_texto(texto),\n",
    "        'segments': segmentos,\n",
    "    })\n",
    "\n",
    "salida = RAW_DIR / 'transcripts_raw.jsonl'\n",
    "with open(salida, 'w', encoding='utf-8') as f:\n",
    "    for row in transcripciones:\n",
    "        f.write(json.dumps(row, ensure_ascii=False) + '\\n')\n",
    "\n",
    "print(f'Transcripciones guardadas : {len(transcripciones)}')\n",
    "print(f'Sin subtítulos (omitidos) : {len(sin_subs)}')\n",
    "print(f'Archivo: {salida}')\n",
]

# ──────────────────────────────────────────────────────────────────────────────
# Aplicar parches
# ──────────────────────────────────────────────────────────────────────────────
INDEX_MAP = {
    2: CELL_INSTALL,
    7: CELL_SELENIUM,
    10: CELL_LISTAR,
    13: CELL_SUBS,
    14: CELL_LOOP,
}

for idx, new_src in INDEX_MAP.items():
    nb['cells'][idx]['source'] = new_src
    nb['cells'][idx]['outputs'] = []
    nb['cells'][idx]['execution_count'] = None
    print(f'  Celda {idx} actualizada.')

with open(NB_PATH, 'w', encoding='utf-8') as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print('\nNotebook guardado correctamente.')

